# Chapter 2 Lab: Introduction to R
Apparently this repo is meant to re-do everything in Python, will use this space to warm up and do some light-weight demonstration of numpy, pandas, ect. as I see equivalent to the R commands demonstrated in this lab
# Basic Commands (2.3.1)

In [2]:
# Create and Update "Vector"
import numpy as np
x = np.array([1, 3, 2, 5])
print(x)
x = np.array([1, 6, 2])
y = np.array([1, 4, 3])
print(y)
print(len(x))
print(len(y))
print(x + y)

[1 3 2 5]
[1 4 3]
3
3
[ 2 10  5]


In [7]:
# create square matrix and do point-wise computation
x = np.array([[1, 2], [3, 4]])
print(x)
print(np.sqrt(x))
print(np.power(x, 2))

[[1 2]
 [3 4]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 1  4]
 [ 9 16]]
